import { Delius, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ChatWidget from "@/components/ChatWidget";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
  display:  "swap",
});

const deliusFont = Delius({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-delius'
});

export const metadata = {
  title: "AY VisualZ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${deliusFont.variable} antialiased`}>
          {/* <Navbar/> */}
          {children}
          <ChatWidget />
      </body>
    </html>
  );
}